version: "1.0"

stages:
  - "clone"
  - "validate"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "RothAndrew/terraform-hcloud-rancher-management-cluster"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  validate_pre-commit:
    title: "Validate pre-commit hooks"
    type: "rothandrew/pre-commit"
    stage: "validate"
    arguments:
      working_directory: '/codefresh/volume/${{CF_REPO_NAME}}'

  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: "ubuntu:latest" # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - "ls"
    stage: "test"
